apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: blackjack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: blackjack-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres-service:5432/postgres
